# s4 configuration
s3_endpoint: http://s3-region.example.com
bucket: s4_test
# tls_no_verify: false
# random_data: false
# disable_keepalive: false

write:
  - name: job1
    recordsize: 1mib
    threadcount: 10
    iterations: 100
  - name: job2
    recordsize: 4mib
    threadcount: 10
    iterations: 100
